version: "3"
services:
  cif_download:
    container_name: cif-download
    build:
      context: "."
      dockerfile: ./docker/cif_download/Dockerfile
    environment:
      CIF_FOLDER: /root/CIF/
      ARCHIVE_CIF: /root/ARCHIVE_CIF
      NROD_USER: ${NROD_USER}
      NROD_PASS: ${NROD_PASS}
    volumes:
    - "/home/tms_user/CIF:/root/CIF/"
    - "/home/tms_user/ARCHIVE_CIF:/root/ARCHIVE_CIF/"
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: TSDB
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080


