version: "3"
services:
  cif_download:
    container_name: cif-download
    build:
      context: "."
      dockerfile: ./docker/cif_download/Dockerfile
    environment:
      CIF_FOLDER: /root/CIF/
      ARCHIVE_CIF: /root/ARCHIVE_CIF
      NROD_USER: ${NROD_USER}
      NROD_PASS: ${NROD_PASS}
    volumes:
      - "/home/tms_user/CIF:/root/CIF/"
      - "/home/tms_user/ARCHIVE_CIF:/root/ARCHIVE_CIF/"
  cif_processing:
    container_name: cif-processing
    build:
      context: "."
      dockerfile: ./docker/cif_processing/Dockerfile
    environment:
      CIF_FOLDER: /root/CIF/
      PROC_DIR: /root/PROC_DIR
    volumes:
      - "/home/tms_user/CIF:/root/CIF/"
      - "/home/tms_user/PROC_DIR:/root/PROC_DIR/"
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: TSDB
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "/db-data:/var/lib/postgresql/data"
      - "/home/tms_user/PROC_DIR:/root/PROC_DIR/"
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api:
    container_name: api
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
    build:
      context: '.'
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 8000:8000